### ISSUE TITLE
Does the project still have the same purpose?

### ISSUE THREAD

**Issue by AntonioVOL** [neoterm/neoterm#1]
I would like to know if this project will remain an Android terminal or what will be done if it is not going to be a terminal. I would like it to remain a terminal because it is one of the best apps I know for this and I am worried that it will disappear.

Best regards.

**Comment by neoterm** [comment]
Sorry for late reply.

It's a terminal project, so don't worry about anything. Still working on this project. Coming soon with awesome modern features and packages. I believe that everyone will love it and be happy. Thanks

**Comment by AntonioVOL** [comment]
Okay. Glad to hear that the project will continue. I'm sure it will surpass termux, I'm looking forward xd

Regards.
