### ISSUE TITLE
Source gone?

### ISSUE THREAD

**Issue by IzzySoft** [neoterm/neoterm#2]
I just wonder where the source went to. There was code available here a year ago, but now it's only the Readme, gitignore and license. Will the source return, or did the app turn proprietary?

**Comment by Martinvlba** [comment]
Its not gone, it was just moved as original author gave this org name for someone else

Original org is still available here: https://github.com/NeoTerrm/NeoTerm

**Comment by neoterm** [comment]
Nothing to say now, will discuss a month later... Let me release first.... tnx

**Comment by IzzySoft** [comment]
So maybe keep the issue open until solved, to serve as a reminder? :wink:

**Comment by Martinvlba** [comment]
Here is the old NeoTerm src before the org switch happened ( @IzzySoft )

https://github.com/NeoTerrm/NeoTerm

**Comment by Martinvlba** [comment]
Here was the old NeoTerm src before the org switch happened

**Comment by IzzySoft** [comment]
Thanks for bringing it back!
